// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmcsemusildpdmasuxuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtY3NlbXVzaWxkcGRtYXN1eHVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4Nzg5NTAsImV4cCI6MjA3MTQ1NDk1MH0.tAiXkdeHDCN2xq12ZkNJ2pXK8Wp5GBW8GFHl401Nk_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});